### PR TITLE
RCDC Doc Updates

### PR DESCRIPTION
**Pull request by bdesmond**
Added a couple of elements that have been added in rollups

### CODE REVIEW

**Comment by PRMerger19** [comment]
@bdesmond : Thanks for your contribution! The author(s) have been notified to review your proposed change. @fimguy

**Comment by chbain** [comment]
@fimguy Unable to assign your alias to this PR, as you may not be in the GitHub org, or under a different alias. Please review this PR and join the GitHub org if needed. 

Here's a link where you can join Microsoft GitHub orgs: https://repos.opensource.microsoft.com/

**Comment by bdesmond** [comment]
@chbain, I think the owner needs to be updated. @fimguy is no longer at MSFT

**Comment by chbain** [comment]
@bdesmond Thank you for the info. I've assigned to the manager (msmbaldwin) as listed in metadata.

**Comment by ktoliver** [comment]
@msmbaldwin Could you review the proposed update and indicate whether the PR can be merged? Thanks.

**Comment by IanBassi** [comment]
I was just starting to try and figure out how to update this page myself when I noticed this Pull Request.  I have reviewed the changes and can confirm they add configuration options which have been added in recent hotfixes.

It will solve issue 181.

**Comment by ktoliver** [comment]
@msmbaldwin

**Comment by ktoliver** [comment]
@msmbaldwin @daveba @billma Would you take a look at this proposed update to a MIMDocs reference article from a year ago? Thank you.

**Comment by ktoliver** [comment]
Review request refresh. Is the PR still in progress?

**Comment by bdesmond** [comment]
This is still relevant/accurate. I can't find Eugene (esergeev) on here but he might have an opinion.

**Pull request merged**
