### PR TITLE
Update deploy-pam-with-windows-server-2016.md

### PR DESCRIPTION
**Pull request by ryanriesMSFT**
Correcting NOTE markdown

### CODE REVIEW

**Comment by ryanriesMSFT** [comment]
Trying to figure out why the NOTE markdown doesn't render. We think perhaps it needs to be all-caps.

**Comment by Jak-MS** [comment]
@barclayn 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

Note @ryanriesMSFT - both [!Note] and [!NOTE] are rendered correctly by the build. (at least in theory)

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ryanriesMSFT** [comment]
@Jak-MS any other ideas as to why the Note sections are not being rendered?

**Review by barclayn — APPROVED** [review]

**Comment by barclayn** [comment]
#sign-off

**Comment by Court72** [comment]
@amycolannino, @SyntaxC4 

FYI: It looks like MIMDocs hasn't been syncing with MIMDocs-pr, so updates merged into the public repo aren't getting published. Can you look into why [they're not syncing](https://review.learn.microsoft.com/en-us/help/onboard/admin/enable-public-contributions?branch=main#set-up-automatic-cross-repository-synchronization)?

**Comment by Court72** [comment]
Merging now.

**Comment by cnotin** [comment]
FYI this warning note is now missing from the page https://learn.microsoft.com/en-us/microsoft-identity-manager/pam/deploy-pam-with-windows-server-2016
Based on [history of this file](https://github.com/MicrosoftDocs/MIMDocs/commits/main/MIMDocs/pam/deploy-pam-with-windows-server-2016.md), it was removed by commit 246819572012e03e5ffbc0658b75a598296b7272 [as you can see after](https://github.com/MicrosoftDocs/MIMDocs/blob/246819572012e03e5ffbc0658b75a598296b7272/MIMDocs/pam/deploy-pam-with-windows-server-2016.md) but I'm not seeing a [change in the diff](https://github.com/MicrosoftDocs/MIMDocs/commit/246819572012e03e5ffbc0658b75a598296b7272#diff-936e0ae0f09056e716a0bdec0d193ffe16cd38c64983affdc857a41c9bf58a8f)

**Pull request merged**
