### PR TITLE
Update step-1-prepare-corp-domain.md

### PR DESCRIPTION
**Pull request by jvheaton**
Update Code Blocks Language Types

### CODE REVIEW

**Comment by PRMerger8** [comment]
@jvheaton : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@jvheaton The update looks good; thanks. Per the [contributor guide](https://docs.microsoft.com/contribute/code-in-docs#fenced-code-blocks), the code fencing should be all lowercase, so I made that edit.

My update triggered a Contributor License Agreement request for you as a newer contributor. Could you sign the CLA? Then, we'll merge the pull request. Thanks.

-PR review team

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @jvheaton!

**Pull request merged**
