### PR TITLE
1199282 - ms.topic update

### PR DESCRIPTION
**Pull request by cmcclister**

### CODE REVIEW

**Comment by cmcclister** [comment]
#sign-off Production 1199282

**Comment by cmcclister** [comment]
Hi @kgremban   please merge this PR when you can so that we can resolve the open issue (meta data update for [1199282](https://mseng.visualstudio.com/CSI/_workitems/edit/1199282)). Thank you.

**Comment by kgremban** [comment]
@barclayn can you help @cmcclister? I don't know what your merging process is like for MIMDocs anymore.

**Comment by barclayn** [comment]
@billmath

**Pull request closed without merging**
