### PR TITLE
Fixed some typos in the code

### PR DESCRIPTION
**Pull request by Cloudenius**
Fixed some typos in the code and added more spacing to make the code block more readable

### CODE REVIEW

**Comment by PRMerger17** [comment]
@jvravensberg : Thanks for your contribution! The author, @billmath, has been notified to review your proposed change.

**Comment by jvravensberg** [comment]
Happy New Year! Thanks for assigning @billmath, @ktoliver. Any update on this pull request?

Thanks!

**Comment by ktoliver** [comment]
Hi @billmath - Would you review the proposed changes? Thanks.

**Comment by ktoliver** [comment]
@billmath (author) @markwahl-msft (reviewer) - Would you review the proposed changes? Thanks.

**Comment by ktoliver** [comment]
@billmath @msmbaldwin @femila Would you be able to review the proposed changes or advise on what action to take with this pull request? Thanks.

**Comment by Cloudenius** [comment]
Closing it as this PR has been open for over a year.

**Pull request closed without merging**
