### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by ganesh-sanap**
fixed typos in article

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ganesh-sanap : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@msmbaldwin Could you review this pull request? The update looks good to me, but do the headings also need a space added after the pound signs? This is reference; can we update directly in the MD file? Thanks.

**Comment by ganesh-sanap** [comment]
@ktoliver @msmbaldwin Any updates on this PR?

**Comment by ktoliver** [comment]
@msmbaldwin Could you verify this update and let me know whether it can be merged here? (Being reference, it might need to be updated elsewhere, if it is an error.) Thanks.

**Comment by PRMerger16** [comment]
@msmbaldwin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
