### PR TITLE
Replace incorrect character in sample code

### LINKED ISSUE #173: Your sample script contains a lot of '–' instead of '-'
@wsy commented on [Mon Jul 29 2019](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/issues/19)

So, your author never noticed the highlighting problem in your sample script.
Only the 'Add-ADGroupMember' and the last two 'Set-ADUser' command have some of their options highlighted and all other parameters in all other commands in this article(except for the Add-ADGroupMember command) failed to be highlighted.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [设置 Microsoft Identity Manager 2016 的域](https://docs.microsoft.com/zh-cn/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/blob/live/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

---

@srvbpigh commented on [Mon Jul 29 2019](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/issues/19#issuecomment-515870817)

Hello, @wsy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

### PR DESCRIPTION
**Pull request by wsy**
Fixes #173 
Your sample code contains "–", which looks like the correct one "-".
However, they're not the same character and they cause your sample code unable to run if you copy and paste them.
I created issue #173 almost one year ago and no one is fixing them.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@wsy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@billmath - Could you review this PR? Thanks.

**Comment by ktoliver** [comment]
@billmath

**Comment by ktoliver** [comment]
Looks correct; merging.

**Pull request merged**
