### PR TITLE
Update step-5-establish-trust-between-priv-corp-forests.md

### PR DESCRIPTION
**Pull request by mistermik**
command should use  /quarantine:NO to disable SID filtering
Command is in fact documented correct in step "Deploy MIM PAM with Windows Server 2016"

### CODE REVIEW

**Comment by mistermik** [comment]
I see this is still pending
Let me be more specific in identify where the issue is:
https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-5-establish-trust-between-priv-corp-forests
"Give forests read access to Active Directory" 
Step: 10.Use netdom to ensure SID history is enabled and SID filtering is disabled. Type:

netdom trust contoso.local /quarantine:NO /domain priv.contoso.local
netdom trust /enablesidhistory:yes /domain priv.contoso.local

Documentation is missing the :NO to disable SID filtering
 Command is in fact documented correct in step "Deploy MIM PAM with Windows Server 2016"

**Comment by barclayn** [comment]
Thank you for your feedback. I have made updates based on this.

**Comment by PRMerger4** [comment]
@mistermik : Thanks for your contribution! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
These changes were already pulled in.

#please-close

**Pull request closed without merging**
