### PR TITLE
Update topology-considerations.md

### PR DESCRIPTION
**Pull request by RKauf00**
Added SQL AoAG supported configuration notice to section likely to referenced by individuals designed a new solution; existing notice under "Deploy and Use" --> "First Time Deployment" --> "Server Setup: SQL" is routinely overlooked.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@RKauf00 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Admin note: If the PR is approved, the Markdown syntax for the custom alert needs to be fixed before merging. The PR review team can do this.

**Comment by ktoliver** [comment]
@billmath Could you review this proposed update to your article?

Thank you!

**Comment by ktoliver** [comment]
@billmath Could you let us know whether this pull request from last October being reviewed?

Thanks.

**Comment by Jak-MS** [comment]
@billmath  - nudge

**Review by EugeneSergeev — CHANGES_REQUESTED** [review]
AoAG mentioned here: https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sql2016

no need to include it here

**Comment by ShannonLeavitt** [comment]
Closing per the PR per Eugene's comment above.

**Pull request closed without merging**
