### PR TITLE
Fix URL for SessionInfo Endpoint

### PR DESCRIPTION
**Pull request by Turninator95**
URL was wrong. Instead of /api/session/sessioninfo it is /api/pamresources/sessioninfo.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@Turninator95 : Thanks for your contribution! The author, @msmbaldwin, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @msmbaldwin - Could you review the proposed changes? Thank you.

**Comment by PRMerger9** [comment]
@Turninator95 : Thanks for your contribution! The author, @msmbaldwin, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@markwahl-msft (reviewer) @msmbaldwin (author) Could you make a determination of whether the suggested update is correct? Then, we can either merge or close the PR. Thanks!

**Comment by markwahl-msft** [comment]
This fix is correct, the documentation should have stated pamresources/sessioninfo.

**Pull request merged**
