### PR TITLE
chore: Fix index page warning formatting

### PR DESCRIPTION
**Pull request by nschonni**
Wasn't rendering correctly on https://docs.microsoft.com/en-us/microsoft-identity-manager/

### CODE REVIEW

**Comment by GitHubber17** [comment]
@barclayn - Would you review the proposed changes? Thanks

**Comment by tfosmark** [comment]
This article has been substantially updated, so this fix is no longer necessary. Thank you for your contribution!

**Comment by nschonni** [comment]
Is the updates pending a release? I'm still seeing the broken rendering today
image

**Comment by tfosmark** [comment]
@nschonni I see it, too. We'll get this fix in today. Thank you!

**Pull request closed without merging**
